name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
